//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIManagment.ModuleCore.Data.DataSource.Local.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarColor
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string NameRU { get; set; }
        public string ColorNameRU { get; set; }
        public bool IsMetallic { get; set; }
        public string NameEN { get; set; }
        public string ColorNameEN { get; set; }
    }
}
