//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIManagment.ModuleCore.Data.DataSource.Local.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int ID { get; set; }
        public string CarNum { get; set; }
        public string Region { get; set; }
        public string LicenceNum { get; set; }
        public string Photo { get; set; }
    
        public virtual Fine Fine1 { get; set; }
        public virtual Fine Fine2 { get; set; }
    }
}
