//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIManagment.ModuleCore.Data.DataSource.Local.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseStatusHistory
    {
        public int ID { get; set; }
        public int LicenseID { get; set; }
        public int StatusID { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
    
        public virtual License License { get; set; }
        public virtual Status Status { get; set; }
    }
}
