//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIManagment.ModuleCore.Data.DataSource.Local.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionCode
    {
        public int ID { get; set; }
        public string RegionNameEN { get; set; }
        public string RegionNameRU { get; set; }
        public string SubjectCode { get; set; }
        public string Code { get; set; }
        public string OKATOCode { get; set; }
        public string ISO { get; set; }
    }
}
