//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAIManagment.ModuleCore.Data.DataSource.Local.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int ID { get; set; }
        public string VIN { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public int Weight { get; set; }
        public int ColorID { get; set; }
        public int EngineType { get; set; }
        public string TypeOfDrive { get; set; }
    }
}
